# kick: 0

version: 2.1

orbs:
  win: circleci/windows@2.2.0

commands:
  run_tests_windows:
    description: "Build libyuv-node and run the test suite"
    parameters:
      version:
        type: string
    steps:
      - run: choco install cmake
      - run_tests:
          version: << parameters.version >>
          os: "windows"
  run_tests_linux:
    description: "Build libyuv-node and run the test suite"
    parameters:
      version:
        type: string
    steps:
      - run: sudo apt update && sudo apt install cmake
      - run_tests:
          version: << parameters.version >>
          os: "linux"
  run_tests:
    description: "Build libyuv-node and run the test suite"
    parameters:
      version:
        type: string
      os:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-<< parameters.os >>-<< parameters.version >>-{{ checksum "package.json" }}
          - v1-dependencies-<< parameters.os >>-<< parameters.version >>-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-<< parameters.os >>-<< parameters.version >>-{{ checksum "package.json" }}
      - run: npm test
jobs:
  windows-node-18:
    executor:
      name: win/default
      size: medium
    steps:
      - run_tests_windows:
          version: "18"
  linux-node-26:
    docker:
      - image: circleci/node:26
    working_directory: ~/repo
    steps:
      - run_tests_linux:
          version: "14"
  linux-node-22:
    docker:
      - image: circleci/node:22
    working_directory: ~/repo
    steps:
      - run_tests_linux:
          version: "12"
  linux-node-18:
    docker:
      - image: circleci/node:18
    working_directory: ~/repo
    steps:
      - run_tests_linux:
          version: "10"

workflows:
  build:
    jobs:
      - windows-node-18
      - linux-node-26
      - linux-node-22
      - linux-node-18
